### ISSUE TITLE
Create new action on push to paper.md or paper.bib with the following content

### ISSUE THREAD

**Issue by abuzarmahmood** [abuzarmahmood/pytau#74]
- name: Open Journals PDF Generator
    uses: openjournals/openjournals-draft-action@v.1.0

Ref: https://github.com/marketplace/actions/open-journals-pdf-generator

**Comment by abuzarmahmood** [comment]
The issue involves creating a new GitHub Action that triggers on a push to `paper.md` or `paper.bib` files in the `abuzarmahmood/pytau` repository. The action should use the `openjournals/openjournals-draft-action@v.1.0`.

### Suggestions and Changes Made:

1. **File Identification**:
   - A new workflow file should be created in the `.github/workflows` directory. The existing `pytest_workflow.yml` file can be used as a reference.

2. **Suggested Modifications**:
   - **Create a New Workflow File**: 
     - **File**: `.github/workflows/openjournals_pdf_generator.yml`
     - **Description**: This file will define a workflow that triggers on pushes to `paper.md` or `paper.bib` and runs the Open Journals PDF Generator action.
     - **Code Snippet**:
       ```yaml
       name: Open Journals PDF Generator

       on:
         push:
           paths:
             - 'paper.md'
             - 'paper.bib'

       jobs:
         generate-pdf:
           runs-on: ubuntu-latest

           steps:
           - uses: actions/checkout@v2
           - name: Open Journals PDF Generator
             uses: openjournals/openjournals-draft-action@v.1.0
       ```

This new workflow will ensure that the Open Journals PDF Generator action is executed whenever there is a push to either `paper.md` or `paper.bib`, fulfilling the user's request.

---
*This response was automatically generated by blech_bot using model gpt-4o*

**Comment by abuzarmahmood** [comment]
Incorporate the following info as well

```
name: Draft PDF
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper.pdf
```

**Comment by abuzarmahmood** [comment]
Path to paper material is actually `JOSS_submission/paper.md`

**Comment by abuzarmahmood** [comment]
Based on the feedback and the existing workflow file structure, here's an updated response that incorporates the additional information provided by the user:

### Updated Suggestions and Changes:

1. **File Identification**:
   - A new workflow file should be created in the `.github/workflows` directory. The existing `pytest_workflow.yml` file can be used as a reference for structure and syntax.

2. **Suggested Modifications**:
   - **Create a New Workflow File**: 
     - **File**: `.github/workflows/openjournals_pdf_generator.yml`
     - **Description**: This file will define a workflow that triggers on pushes to `JOSS_submission/paper.md` or `JOSS_submission/paper.bib` and runs the Open Journals PDF Generator action.
     - **Code Snippet**:
       ```yaml
       name: Draft PDF

       on:
         push:
           paths:
             - 'JOSS_submission/paper.md'
             - 'JOSS_submission/paper.bib'

       jobs:
         paper:
           runs-on: ubuntu-latest
           name: Paper Draft

           steps:
           - name: Checkout
             uses: actions/checkout@v4
           - name: Build draft PDF
             uses: openjournals/openjournals-draft-action@master
             with:
               journal: joss
               paper-path: JOSS_submission/paper.md
           - name: Upload
             uses: actions/upload-artifact@v4
             with:
               name: paper
               path: paper.pdf
       ```

This updated workflow will ensure that the Open Journals PDF Generator action is executed whenever there is a push to either `JOSS_submission/paper.md` or `JOSS_submission/paper.bib`, and it includes additional steps for building and uploading the draft PDF as specified in the user feedback.

---
*This response was automatically generated by blech_bot using model gpt-4o*
