### ISSUE TITLE
Packaging and publishing using github workflow

### ISSUE THREAD

**Issue by abuzarmahmood** [abuzarmahmood/pytau#87]
Triggered when a pull request is merged or a new version is tagged.
Can use UV? https://github.com/astral-sh/uv

**Comment by abuzarmahmood** [comment]
### Summary of Suggestions and Changes

1. **Identified Files for Modification:**
   - **File:** `.github/workflows/openjournals_pdf_generator.yml`
     - **Description:** This workflow generates a draft PDF for JOSS submissions. It could be modified to include packaging and publishing steps if related to JOSS submissions.
   - **File:** `.github/workflows/pytest_workflow.yml`
     - **Description:** This workflow runs tests using Pytest on pushes to the main branch and pull requests. It can be extended to include packaging and publishing steps when a pull request is merged or a new version is tagged.

2. **Plan to Address the Issue:**
   - Modify existing GitHub workflows to include steps for packaging and publishing.
   - Integrate UV, a Python package and project manager, into the workflow for package management.
   - Ensure the workflow triggers on pull request merges and new version tags.

3. **Specific Changes Suggested:**
   - **Add Packaging and Publishing Steps to Pytest Workflow:**
     - **File:** `.github/workflows/pytest_workflow.yml`
     - **Line:** After line 26
     - **Description:** Add steps to package and publish the project using UV when a pull request is merged or a new version is tagged.
     - **Code Snippet:**
       ```yaml
       - name: Install UV
         run: |
           curl -sSf https://sh.rustup.rs | sh -s -- -y
           source $HOME/.cargo/env
           cargo install uv

       - name: Package and Publish
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: |
           uv package
           uv publish
       ```

   - **Modify Workflow Triggers:**
     - **File:** `.github/workflows/pytest_workflow.yml`
     - **Line:** 2-6
     - **Description:** Modify the workflow triggers to include pull request merges and new version tags.
     - **Code Snippet:**
       ```yaml
       on:
         push:
           branches: [ main ]
         pull_request:
           branches: [ '**' ]
         release:
           types: [created]
       ```

These changes aim to ensure that the project is packaged and published using UV whenever a pull request is merged into the main branch or a new version is tagged, thereby streamlining the packaging process.

---
*This response was automatically generated by blech_bot using model gpt-4o*
